site_name: pymaplibregl

theme:
  name: material
  # custom_dir: mkdocs_overrides

nav:
  - index.md
  # - example.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: list
            show_root_heading: true
            show_source: True
