site_name: MapLibre for Python

theme:
  name: material
  custom_dir: docs/theme
  palette:
    primary: "green"
  features:
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - Get started:
      - Welcome to MapLibre: index.md
      - Layers: layers.md
      - Shiny: shiny.md
      - Jupyter: jupyter.md
  - API Documentation:
      - Map: api/map.md
      - Layer: api/layer.md
      - Sources: api/sources.md
      - Basemaps: api/basemaps.md
      - Markers and controls: api/controls.md
  - Examples:
      - Every person in manhattan: examples/every_person_in_manhattan/index.md
      - Vancouver property value: examples/vancouver_blocks/index.md
      - Earthquake clusters: examples/earthquake_clusters/index.md
      - Airport markers: examples/airports/index.md
      - 3D Indoor mapping: examples/3d_indoor_mapping/index.md
      - Custom basemap: examples/custom_basemap/index.md
      - GeoPandas: examples/geopandas/index.md
      - H3 Grid UK Road Safety: examples/road_safety/index.md
      - Where is the ISS: examples/where_is_the_iss/index.md

plugins:
  - search:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: table
            show_root_heading: true
            show_source: True

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - pymdownx.snippets:
      check_paths: true
      base_path: [docs/examples, "."]

repo_name: py-maplibregl
repo_url: https://github.com/eodaGmbH/py-maplibregl